package com.giglister.service;

import com.giglister.domain.Band;
import com.giglister.domain.BandFollow;
import com.giglister.domain.BandLineupEntry;
import com.giglister.domain.Claim;
import com.giglister.domain.DeviceToken;
import com.giglister.domain.DismissedDuplicate;
import com.giglister.domain.EntityMerge;
import com.giglister.domain.EntityPermission;
import com.giglister.domain.Event;
import com.giglister.domain.EventSeries;
import com.giglister.domain.Location;
import com.giglister.domain.SavedAct;
import com.giglister.domain.SavedEvent;
import com.giglister.domain.Submission;
import com.giglister.domain.User;
import com.giglister.exception.BadRequestException;
import com.giglister.repository.BandFollowRepository;
import com.giglister.repository.BandRepository;
import com.giglister.repository.ClaimRepository;
import com.giglister.repository.DeviceTokenRepository;
import com.giglister.repository.DismissedDuplicateRepository;
import com.giglister.repository.EntityMergeRepository;
import com.giglister.repository.EntityPermissionRepository;
import com.giglister.repository.EventRepository;
import com.giglister.repository.EventSeriesRepository;
import com.giglister.repository.LocationRepository;
import com.giglister.repository.SavedActRepository;
import com.giglister.repository.SavedEventRepository;
import com.giglister.repository.SubmissionRepository;
import com.giglister.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * "Alle Daten exportieren/importieren" - a full snapshot of every row in every table, for
 * backup/restore or moving data between environments (e.g. staging -> prod). Deliberately
 * whole-database, not per-entity: nothing in this schema has a real FK constraint tying
 * one of these tables to another (see the comment on TABLES below) - that only holds
 * together by convention as long as every table is replaced together, so a partial import
 * would leave dangling ids with nothing to notice.
 *
 * Import writes go through plain JdbcTemplate INSERTs, not the JPA repositories/entity
 * manager: every id here is GENERATED BY DEFAULT AS IDENTITY (plain INSERT can set it
 * explicitly - see importAll), but JPA's own save()/persist() always either generates a
 * fresh id or treats a non-null one as "this row already exists, UPDATE it" - neither is
 * "insert this exact row with this exact id" for data that doesn't exist yet in a just-
 * truncated table. Hibernate's Session#replicate looked like the built-in answer to
 * exactly that, but its collection handling isn't reliable for an @ElementCollection with
 * an @OrderColumn (event_band): it can double-insert the same (event_id, position) row,
 * a real duplicate-key failure caught by hand against local Postgres before this ever
 * reached a real deployment - plain JDBC has no such ambiguity to trip over.
 */
@Service
@RequiredArgsConstructor
public class DataTransferService {

    /** Required verbatim on an import request - a guard independent of whatever the
     * frontend's own confirmation UI does, since this replaces every row in every table
     * with no way back once committed. */
    public static final String CONFIRMATION_PHRASE = "ALLE DATEN ERSETZEN";

    private final UserRepository userRepository;
    private final BandRepository bandRepository;
    private final LocationRepository locationRepository;
    private final EventSeriesRepository eventSeriesRepository;
    private final EventRepository eventRepository;
    private final BandFollowRepository bandFollowRepository;
    private final SavedEventRepository savedEventRepository;
    private final SavedActRepository savedActRepository;
    private final EntityPermissionRepository entityPermissionRepository;
    private final ClaimRepository claimRepository;
    private final EntityMergeRepository entityMergeRepository;
    private final DismissedDuplicateRepository dismissedDuplicateRepository;
    private final SubmissionRepository submissionRepository;
    private final DeviceTokenRepository deviceTokenRepository;
    private final JdbcTemplate jdbcTemplate;

    public record DataExport(
            Instant exportedAt,
            List<User> users,
            List<Band> bands,
            List<Location> locations,
            List<EventSeries> eventSeries,
            List<Event> events,
            List<BandFollow> bandFollows,
            List<SavedEvent> savedEvents,
            List<SavedAct> savedActs,
            List<EntityPermission> entityPermissions,
            List<Claim> claims,
            List<EntityMerge> entityMerges,
            List<DismissedDuplicate> dismissedDuplicates,
            List<Submission> submissions,
            List<DeviceToken> deviceTokens
    ) {
    }

    public record ImportRequest(String confirm, DataExport data) {
    }

    public record ImportResult(int tablesReplaced, int rowsImported) {
    }

    public DataExport exportAll() {
        return new DataExport(
                Instant.now(),
                userRepository.findAll(),
                bandRepository.findAll(),
                locationRepository.findAll(),
                eventSeriesRepository.findAll(),
                eventRepository.findAll(),
                bandFollowRepository.findAll(),
                savedEventRepository.findAll(),
                savedActRepository.findAll(),
                entityPermissionRepository.findAll(),
                claimRepository.findAll(),
                entityMergeRepository.findAll(),
                dismissedDuplicateRepository.findAll(),
                submissionRepository.findAll(),
                deviceTokenRepository.findAll()
        );
    }

    /** Every table this covers: each entity's own table, plus the three @ElementCollection
     * tables (band_genre/event_band/user_preferred_genre) that ride along with their
     * owning entity below rather than getting their own DataExport list. Listed together
     * in one TRUNCATE so Postgres resolves the (few, collection-only) FK constraints
     * between them internally, whatever order they're named in. */
    private static final String[] TABLES = {
            "app_user", "user_preferred_genre",
            "band", "band_genre",
            "location",
            "event_series",
            "event", "event_band",
            "band_follow", "saved_event", "saved_act",
            "entity_permission", "claim", "entity_merge", "dismissed_duplicate",
            "submission", "device_token"
    };

    /** The subset of TABLES with their own `id` IDENTITY sequence - band_genre/event_band/
     * user_preferred_genre aren't in here, they have no id column of their own. */
    private static final String[] TABLES_WITH_ID_SEQUENCE = {
            "app_user", "band", "location", "event_series", "event", "band_follow", "saved_event",
            "saved_act", "entity_permission", "claim", "entity_merge", "dismissed_duplicate",
            "submission", "device_token"
    };

    /** Replaces every row in every table with exactly what's in `request.data()` - not a
     * merge. Wiping first (inside the same transaction as the re-import below) means a
     * failure partway through the import rolls the TRUNCATE back too, leaving the
     * original data untouched rather than a half-imported mix. */
    @Transactional
    public ImportResult importAll(ImportRequest request) {
        if (!CONFIRMATION_PHRASE.equals(request.confirm())) {
            throw new BadRequestException("Bestätigung fehlt oder stimmt nicht - nichts wurde geändert");
        }
        DataExport data = request.data();
        jdbcTemplate.execute("TRUNCATE TABLE " + String.join(", ", TABLES) + " RESTART IDENTITY CASCADE");

        int rows = 0;
        rows += insertUsers(data.users());
        rows += insertBands(data.bands());
        rows += insertLocations(data.locations());
        rows += insertEventSeries(data.eventSeries());
        rows += insertEvents(data.events());
        rows += insertBandFollows(data.bandFollows());
        rows += insertSavedEvents(data.savedEvents());
        rows += insertSavedActs(data.savedActs());
        rows += insertEntityPermissions(data.entityPermissions());
        rows += insertClaims(data.claims());
        rows += insertEntityMerges(data.entityMerges());
        rows += insertDismissedDuplicates(data.dismissedDuplicates());
        rows += insertSubmissions(data.submissions());
        rows += insertDeviceTokens(data.deviceTokens());
        resyncIdSequences();
        return new ImportResult(TABLES.length, rows);
    }

    /** Every insert above sets `id` explicitly rather than going through the IDENTITY
     * column's own DEFAULT, so none of them ever draw from (or advance) that column's
     * sequence - left alone, it would still read back as 1 from RESTART IDENTITY above,
     * and the next real signup/create anywhere would collide with the lowest id this
     * import just wrote. Fast-forwards each sequence to one past the highest id actually
     * imported (or leaves it at 1 for a table nothing was imported into) - the same
     * "resync from data already written, since the DB has no way to know that number
     * until asked" situation EnumCheckConstraintSync exists for on the schema side. */
    private void resyncIdSequences() {
        for (String table : TABLES_WITH_ID_SEQUENCE) {
            jdbcTemplate.queryForObject("SELECT setval(pg_get_serial_sequence(?, 'id'), "
                    + "COALESCE((SELECT MAX(id) + 1 FROM " + table + "), 1), false)", Long.class, table);
        }
    }

    private int insertUsers(List<User> users) {
        if (isEmpty(users)) return 0;
        List<Object[]> rows = new ArrayList<>();
        List<Object[]> genreRows = new ArrayList<>();
        for (User u : users) {
            rows.add(new Object[]{u.getId(), u.getEmail(), u.getPasswordHash(), u.getUsername(), u.isEmailVerified(),
                    u.getVerificationToken(), ts(u.getVerificationTokenExpiresAt()), u.getResetToken(), ts(u.getResetTokenExpiresAt()),
                    u.getHomeCity(), u.getHomeLatitude(), u.getHomeLongitude(), u.getRadiusKm(),
                    u.isPlatformAdmin(), u.getMustChangePassword(), ts(u.getCreatedAt())});
            if (u.getPreferredGenres() != null) {
                for (String genre : u.getPreferredGenres()) {
                    genreRows.add(new Object[]{u.getId(), genre});
                }
            }
        }
        jdbcTemplate.batchUpdate("INSERT INTO app_user (id, email, password_hash, username, email_verified, "
                + "verification_token, verification_token_expires_at, reset_token, reset_token_expires_at, "
                + "home_city, home_latitude, home_longitude, radius_km, platform_admin, must_change_password, created_at) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        if (!genreRows.isEmpty()) {
            jdbcTemplate.batchUpdate("INSERT INTO user_preferred_genre (user_id, genre) VALUES (?, ?)", genreRows);
        }
        return rows.size();
    }

    private int insertBands(List<Band> bands) {
        if (isEmpty(bands)) return 0;
        List<Object[]> rows = new ArrayList<>();
        List<Object[]> genreRows = new ArrayList<>();
        for (Band b : bands) {
            rows.add(new Object[]{b.getId(), b.getName(), b.getCity(), b.getCountry(), b.getShortDescription(),
                    b.getWebsite(), b.getLogoUrl(), b.getTitleImageUrl(), en(b.getStatus()), b.getCreatedBy(),
                    ts(b.getCreatedAt()), ts(b.getUpdatedAt())});
            if (b.getGenres() != null) {
                for (String genre : b.getGenres()) {
                    genreRows.add(new Object[]{b.getId(), genre});
                }
            }
        }
        jdbcTemplate.batchUpdate("INSERT INTO band (id, name, city, country, short_description, website, logo_url, "
                + "title_image_url, status, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        if (!genreRows.isEmpty()) {
            jdbcTemplate.batchUpdate("INSERT INTO band_genre (band_id, genre) VALUES (?, ?)", genreRows);
        }
        return rows.size();
    }

    private int insertLocations(List<Location> locations) {
        if (isEmpty(locations)) return 0;
        List<Object[]> rows = new ArrayList<>();
        for (Location l : locations) {
            rows.add(new Object[]{l.getId(), l.getName(), l.getCity(), l.getAddress(), l.getPostalCode(), l.getCountry(),
                    l.getWebsite(), l.getLogoUrl(), l.getTitleImageUrl(), l.getLatitude(), l.getLongitude(),
                    en(l.getStatus()), l.getCreatedBy(), ts(l.getCreatedAt()), ts(l.getUpdatedAt())});
        }
        jdbcTemplate.batchUpdate("INSERT INTO location (id, name, city, address, postal_code, country, website, "
                + "logo_url, title_image_url, latitude, longitude, status, created_by, created_at, updated_at) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertEventSeries(List<EventSeries> series) {
        if (isEmpty(series)) return 0;
        List<Object[]> rows = new ArrayList<>();
        for (EventSeries s : series) {
            rows.add(new Object[]{s.getId(), s.getName(), s.getDescription(), s.getTitleImageUrl(), s.getTicketUrl(),
                    en(s.getTimetableStyle()), s.getCreatedBy(), ts(s.getCreatedAt()), ts(s.getUpdatedAt())});
        }
        jdbcTemplate.batchUpdate("INSERT INTO event_series (id, name, description, title_image_url, ticket_url, "
                + "timetable_style, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertEvents(List<Event> events) {
        if (isEmpty(events)) return 0;
        List<Object[]> rows = new ArrayList<>();
        List<Object[]> lineupRows = new ArrayList<>();
        for (Event e : events) {
            rows.add(new Object[]{e.getId(), e.getTitle(), e.getDate(), e.getStartTime(), e.getLocationId(),
                    e.getDescription(), e.getTicketUrl(), e.getTitleImageUrl(), e.getEventSeriesId(),
                    en(e.getBandImageDisplay()), en(e.getStatus()), e.getCreatedBy(), ts(e.getCreatedAt()), ts(e.getUpdatedAt())});
            List<BandLineupEntry> lineup = e.getBandLineup();
            if (lineup != null) {
                for (int position = 0; position < lineup.size(); position++) {
                    BandLineupEntry entry = lineup.get(position);
                    lineupRows.add(new Object[]{e.getId(), position, entry.getBandId(), entry.getStartTime()});
                }
            }
        }
        jdbcTemplate.batchUpdate("INSERT INTO event (id, title, date, start_time, location_id, description, "
                + "ticket_url, title_image_url, event_series_id, band_image_display, status, created_by, created_at, updated_at) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        if (!lineupRows.isEmpty()) {
            jdbcTemplate.batchUpdate("INSERT INTO event_band (event_id, position, band_id, start_time) VALUES (?, ?, ?, ?)", lineupRows);
        }
        return rows.size();
    }

    private int insertBandFollows(List<BandFollow> follows) {
        if (isEmpty(follows)) return 0;
        List<Object[]> rows = follows.stream()
                .map(f -> new Object[]{f.getId(), f.getUserId(), f.getBandId(), ts(f.getFollowedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO band_follow (id, user_id, band_id, followed_at) VALUES (?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertSavedEvents(List<SavedEvent> saved) {
        if (isEmpty(saved)) return 0;
        List<Object[]> rows = saved.stream()
                .map(s -> new Object[]{s.getId(), s.getUserId(), s.getEventId(), ts(s.getSavedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO saved_event (id, user_id, event_id, saved_at) VALUES (?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertSavedActs(List<SavedAct> saved) {
        if (isEmpty(saved)) return 0;
        List<Object[]> rows = saved.stream()
                .map(s -> new Object[]{s.getId(), s.getUserId(), s.getEventId(), s.getBandId(), ts(s.getSavedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO saved_act (id, user_id, event_id, band_id, saved_at) VALUES (?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertEntityPermissions(List<EntityPermission> permissions) {
        if (isEmpty(permissions)) return 0;
        List<Object[]> rows = permissions.stream()
                .map(p -> new Object[]{p.getId(), p.getUserId(), en(p.getEntityType()), p.getEntityId(),
                        en(p.getPermission()), p.getGrantedBy(), ts(p.getGrantedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO entity_permission (id, user_id, entity_type, entity_id, permission, "
                + "granted_by, granted_at) VALUES (?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertClaims(List<Claim> claims) {
        if (isEmpty(claims)) return 0;
        List<Object[]> rows = claims.stream()
                .map(c -> new Object[]{c.getId(), en(c.getEntityType()), c.getEntityId(), c.getRequestedBy(),
                        c.getMessage(), en(c.getStatus()), c.getDecidedBy(), ts(c.getDecidedAt()), ts(c.getRequestedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO claim (id, entity_type, entity_id, requested_by, message, status, "
                + "decided_by, decided_at, requested_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertEntityMerges(List<EntityMerge> merges) {
        if (isEmpty(merges)) return 0;
        List<Object[]> rows = merges.stream()
                .map(m -> new Object[]{m.getId(), en(m.getEntityType()), m.getSourceEntityId(), m.getTargetEntityId(),
                        m.getSourceNameAlias(), m.getMergedBy(), ts(m.getMergedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO entity_merge (id, entity_type, source_entity_id, target_entity_id, "
                + "source_name_alias, merged_by, merged_at) VALUES (?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertDismissedDuplicates(List<DismissedDuplicate> dismissed) {
        if (isEmpty(dismissed)) return 0;
        List<Object[]> rows = dismissed.stream()
                .map(d -> new Object[]{d.getId(), en(d.getEntityType()), d.getLowerEntityId(), d.getHigherEntityId(),
                        d.getDismissedBy(), ts(d.getDismissedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO dismissed_duplicate (id, entity_type, lower_entity_id, "
                + "higher_entity_id, dismissed_by, dismissed_at) VALUES (?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertSubmissions(List<Submission> submissions) {
        if (isEmpty(submissions)) return 0;
        List<Object[]> rows = submissions.stream()
                .map(s -> new Object[]{s.getId(), en(s.getType()), s.getPayload(), s.getImageUrl(), s.getTargetEntityId(),
                        s.getSubmittedBy(), en(s.getStatus()), ts(s.getSubmittedAt()), s.getReviewedBy(),
                        ts(s.getReviewedAt()), s.getRejectionReason(), s.getResultEntityId()})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO submission (id, type, payload, image_url, target_entity_id, "
                + "submitted_by, status, submitted_at, reviewed_by, reviewed_at, rejection_reason, result_entity_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", rows);
        return rows.size();
    }

    private int insertDeviceTokens(List<DeviceToken> tokens) {
        if (isEmpty(tokens)) return 0;
        List<Object[]> rows = tokens.stream()
                .map(t -> new Object[]{t.getId(), t.getUserId(), t.getToken(), ts(t.getCreatedAt())})
                .toList();
        jdbcTemplate.batchUpdate("INSERT INTO device_token (id, user_id, token, created_at) VALUES (?, ?, ?, ?)", rows);
        return rows.size();
    }

    private boolean isEmpty(List<?> list) {
        return list == null || list.isEmpty();
    }

    private Object ts(Instant instant) {
        return instant == null ? null : Timestamp.from(instant);
    }

    private Object en(Enum<?> value) {
        return value == null ? null : value.name();
    }
}
